import '@/styles/global.css';
import Sidebar from '@/components/sidebar';
import { LayoutRootProps } from '@/interface';
import { NextAuthProvider } from '@/utils/providers/next-auth';
import Navbar from '@/components/navbar';
import Chat from '@/components/global/chat';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout(props: LayoutRootProps) {
  return (
    <html lang='en'>
      <NextAuthProvider>
        <body className='w-full h-screen overflow-y-hidden'>
          <Navbar />
          <section className='w-full flex'>
            <Sidebar />
            <main className='w-full h-[90vh] overwrite-sticky flex-1 p-4'>
              {props.children}
            </main>
          </section>
          <Chat />
        </body>
      </NextAuthProvider>
    </html>
  );
}
