import Navbar from '@/components/navbar';
import '@/styles/global.css';
import { LayoutRootProps } from '@/interface';
import type { Metadata } from 'next';
import { NextAuthProvider } from '@/utils/providers/next-auth';

export const metadata: Metadata = {
  title: 'Devspace | Packages',
  description: 'Generated by create next app',
};

export default function RootLayout(props: LayoutRootProps) {
  return (
    <html lang='en'>
      <NextAuthProvider>
        <body>
          <Navbar />
          <main>{props.children}</main>
        </body>
      </NextAuthProvider>
    </html>
  );
}
